#import "模板.typ": *
#show: template-style
#theme.update(red)
#let theme_basic = red
= 1<data:item_data>
== <sec:entity_data>
#heading(level: 4, numbering: none, [实体共通标签])<data:tags_common_to_all_entities>
所有实体拥有以下字段：
#tree(
  (0, [#icon("nbt-compound") 根标签]),
  (1, [#icon("nbt-short") *Air*: 该实体剩余的空气值。]),
  (1, [#icon("nbt-string")#icon("nbt-list")#icon("nbt-compound") *CustomName*: 该实体的自定义名称，未指定名称时该标签不存在。需要是一个文本组件。]),
  (1, [#icon("nbt-bool") *CustomNameVisible*: 该实体的自定义名称能否总是显示在该实体的上方，未指定名称时不存在。]),
  (1, [#icon("nbt-string")#icon("nbt-compound") *data*: 任意自定义数据。写入数据的时候可以使用 #icon("nbt-string") 字符串形式，但存储的时候一律存储为 #icon("nbt-compound") 复合标签形式。]),
  (2, [自定义数据结构]),
  (1, [#icon("nbt-double") *#underline[fall_distance]*: 该实体已下坠的距离。]),
  (1, [#icon("nbt-short") *#underline[Fire]*: 该实体身上的火焰距熄灭的剩余游戏刻时长。对于未着火的玩家，此值为 `-20s`，对于未着火的其他实体，此值为 `-1s`。]),
  (1, [#icon("nbt-bool") *Glowing*: 该实体是否发光。]),
  (1, [#icon("nbt-bool") *HasVisualFire*: 该实体是否在外观上有着火效果。]),
  (1, [#icon("nbt-string") *#underline[id]*: 该实体的命名空间ID，此值不可被修改，根实体的此字段无法被 `/data` 查询。]),
  (1, [#icon("nbt-bool") *#underline[Invulnerable]*: 该实体是否会受到伤害。这里的伤害是指除创造模式玩家造成的伤害和属于伤害类型标签 `#bypasses_invulnerability` 以外的其他伤害。]),
  (1, [#icon("nbt-list") *#underline[Motion]*: 列表中存在3个元素，均为双精度浮点数，用于表示该实体在当前游戏刻的速度。在三维空间中将速度矢量分解为沿3个坐标轴的速度矢量，即$"d"x$、$"d"y$和$"d"z$，分别用此列表第0、1、2个元素表示。]),
  (1, [#icon("nbt-bool") *NoGravity*: 该实体是否会受到重力影响。]),
  (1, [#icon("nbt-bool") *#underline[OnGround]*: 该实体是否接触地面。]),
  (1, [#icon("nbt-list") *Passengers*: 骑乘该实体的实体。]),
  (2, [#icon("nbt-compound") 一个骑乘该实体的实体。]),
  (3, link(<sec:entity_data>)[实体格式]),
  (1, [#icon("nbt-int") *#underline[PortalCooldown]*: 该实体距下次被允许穿过下界传送门前往另一维度的游戏刻。]),
  (1, [#icon("nbt-list") *#underline[Pos]*: 该实体的三维坐标，列表内元素顺序不可改变。]),
  (2, [#icon("nbt-double") $x$坐标。]),
  (2, [#icon("nbt-double") $y$坐标。]),
  (2, [#icon("nbt-double") $z$坐标。]),
  (1, [#icon("nbt-list") *#underline[Rotation]*: 该实体的朝向，列表内元素顺序不可改变。]),
  (2, [#icon("nbt-float") 偏航角。]),
  (2, [#icon("nbt-float") 俯仰角。]),
  (1, [#icon("nbt-bool") *Silent*: 该实体是否会发出声音。]),
  (1, [#icon("nbt-list") *Tags*: 该实体的所有记分板标签。]),
  (2, [#icon("nbt-compound") 一个记分板标签。]),
  (1, [#icon("nbt-int") *TicksFrozen*: 可能不存在，表示实体已冷冻的时间。当实体在细雪中时每游戏刻增加 `1`，离开细雪则每游戏刻减少 `2`。为 `0` 时此标签不存在。]),
  (1, [#icon("nbt-int_array") *#underline[UUID]*: 该实体的UUID。])
)
#heading(level: 4, numbering: none, [生物共通标签（Java类名 `LivingEntity`）])
所有属于生物一类的实体都拥有以下字段：
#tree(
  (0, [#icon("nbt-compound") 根标签]),
  (1, [#icon("nbt-float") *#underline[AbsorptionAmount]*: 此生物的伤害吸收值。]),
  (1, [#icon("nbt-list") *active_effects*: 该生物拥有的状态效果列表。]),
  (2, [#icon("nbt-compound") 一个状态效果。]),
  (3, [#icon("nbt-bool") *ambient*: 该状态效果是否由信标施加。]),
  (3, [#icon("nbt-byte") *amplifier*: 该状态效果的倍率。若实际倍率大于127，设实际倍率为$s$，此标签存储的值为$127-s$。]),
  (3, [#icon("nbt-int") *duration*: 状态效果的持续时间，单位为游戏刻。如果持续时间为无尽，则值为 `-1`。]),
  (3, [#icon("nbt-compound") *hidden_effect*: 存储类型、命名空间ID相同但倍率较低的状态效果，在高倍率状态效果结束后该状态效果会出现，是为低倍率状态效果提供隐藏功能的标签。]),
  (4, [不包含字段 #icon("nbt-string") `id` 的状态效果格式]),
  (3, [#icon("nbt-string") *#underline[id]*: 该状态效果的ID。]),
  (3, [#icon("nbt-bool") *show_icon*: 是否显示图标。]),
  (3, [#icon("nbt-bool") *show_particles*: 是否显示粒子效果。]),
  (1, [#icon("nbt-list") *attributes*: 该实体的属性列表。]),
  (2, [#icon("nbt-compound") 一个属性。]),
  (3, [#icon("nbt-double") *#underline[base]*: 该属性的基值。]),
  (3, [#icon("nbt-string") *#underline[id]*: 该属性的名称，使用命名空间ID。]),
  (3, [#icon("nbt-list") *modifiers*: 属性修饰符列表。]),
  (4, [#icon("nbt-compound") 一个属性修饰符。]),
  (5, [#icon("nbt-double") *#underline[amount]*: 该修饰符的修饰量。]),
  (5, [#icon("nbt-string") *#underline[id]*: 该修饰符的命名空间ID。]),
  (5, [#icon("nbt-string") *#underline[operation]*: 运算模式，可用值为 `add_value`（属性增量）、`add_multiplied_total`（倍率增量）和 `add_multiplied_base`（最终倍乘）。]),
  (1, [#icon("nbt-compound") *Brain*: 生物记忆的相关信息，用于AI计算。不使用生物记忆的实体该项标签为空。]),
  (2, [#icon("nbt-compound") *#underline[memories]*: 生物记忆。此处存储长期记忆，不存储短期记忆，短期记忆仅存在于内存中临时使用。]),
  (3, [#icon("nbt-compound") *minecraft:admiring_disabled*: 适用于*猪灵*，当玩家伤害猪灵时猪灵获得该记忆，并收起金锭停止以物易物。]),
  (4, [#icon("nbt-long") *ttl*: 该记忆距离过期的游戏刻数。初始过期时间为400 gt，此值为 `0l` 时该记忆被删除。]),
  (4, [#icon("nbt-bool") *value*: 猪灵是否拒绝以物易物，记忆存在时总是为 `true`。]),
  (3, [#icon("nbt-compound") *minecraft:admiring_item*: 适用于*猪灵*以物易物时端详物品的记忆。]),
  (4, [#icon("nbt-long") *ttl*: 该记忆距离过期的游戏刻数。初始过期时间为119 gt，此值为 `0l` 时该记忆被删除。]),
  (4, [#icon("nbt-bool") *value*: 猪灵是否正在端详物品，记忆存在时总是为 `true`。]),
  (3, [#icon("nbt-compound") *minecraft:angry_at*: 适用于*猪灵*、*猪灵蛮兵*、*鹦鹉螺*和*僵尸鹦鹉螺*攻击目标的记忆。]),
  (4, [#icon("nbt-long") *ttl*: 该记忆距离过期的游戏刻数。初始过期时间为600 gt，此值为 `0l` 时该记忆被删除。]),
  (4, [#icon("nbt-int_array") *value*: 该猪灵或猪灵蛮兵攻击目标的UUID。]),
  (3, [#icon("nbt-compound") *minecraft:attack_target_cooldown*: 适用于*鹦鹉螺*、*僵尸鹦鹉螺*寻找攻击目标时的冷却状态的记忆。]),
  (4, [#icon("nbt-long") *ttl*: 该记忆距离过期的游戏刻数。初始过期时间是介于400 gt和3600 gt之间（含）的随机数。]),
  (4, [#icon("nbt-int") *value*: 该鹦鹉螺或僵尸鹦鹉螺是否处于寻找攻击目标的冷却状态。]),
  (3, [#icon("nbt-compound") *minecraft:breeze_jump_cooldown*: 适用于*旋风人*进行长跳的冷却时间记忆。]),
  (4, [#icon("nbt-long") *ttl*: 该记忆距离过期的游戏刻数。长跳期间没有被其他生物伤害时，初始过期时间为2 gt，否则为10 gt。]),
  (4, [#icon("nbt-compound") *value*: 无数据，空白复合标签。]),
  (3, [#icon("nbt-compound") *minecraft:breeze_jump_inhaling*: 适用于*旋风人*长跳准备状态的记忆。]),
  (4, [#icon("nbt-long") *ttl*: 该记忆距离过期的游戏刻数。初始过期时间为10 gt。]),
  (4, [#icon("nbt-compound") *value*: 无数据，空白复合标签。]),
  (3, [#icon("nbt-compound") *minecraft:breeze_jump_target*: 适用于*旋风人*长跳目标位置的记忆。]),
  (4, [#icon("nbt-int_array") *value*: 目标位置的方块坐标，列表内元素依次为$x$、$y$、$z$坐标。]),
  (3, [#icon("nbt-compound") *minecraft:breeze_leaving_water*: 适用于*旋风人*离开水中的记忆的记忆。]),
  (4, [#icon("nbt-compound") *value*: 无数据，空白复合标签。]),
  (3, [#icon("nbt-compound") *minecraft:breeze_shoot*: 适用于*旋风人*发射风弹的记忆。]),
  (4, [#icon("nbt-long") *ttl*: 该记忆距离过期的游戏刻数。如果具有攻击对象则获得此记忆，初始过期时间为60 gt。在长跳结束后，旋风人也会获得此记忆，初始过期时间为100 gt。当旋风人受困时也会获得此记忆，初始过期时间为100 gt。]),
  (4, [#icon("nbt-compound") *value*: 无数据，空白复合标签。]),
  (3, [#icon("nbt-compound") *minecraft:breeze_shoot_charging*: 适用于*旋风人*风弹蓄能状态的记忆。]),
  (4, [#icon("nbt-long") *ttl*: 该记忆距离过期的游戏刻数。初始过期时间为10 gt。]),
  (4, [#icon("nbt-compound") *value*: 无数据，空白复合标签。]),
  (3, [#icon("nbt-compound") *minecraft:breeze_shoot_cooldown*: 适用于*旋风人*风弹冷却状态的记忆。]),
  (4, [#icon("nbt-long") *ttl*: 该记忆距离过期的游戏刻数。初始过期时间为10 gt。]),
  (4, [#icon("nbt-compound") *value*: 无数据，空白复合标签。]),
  (3, [#icon("nbt-compound") *minecraft:breeze_shoot_recover*: 适用于*旋风人*风弹准备状态的记忆。]),
  (4, [#icon("nbt-long") *ttl*: 该记忆距离过期的游戏刻数。初始过期时间为4 gt。]),
  (4, [#icon("nbt-compound") *value*: 无数据，空白复合标签。]),
  (3, [#icon("nbt-compound") *minecraft:charge_cooldown_ticks*: 适用于*鹦鹉螺*、*僵尸鹦鹉螺*冲刺攻击时的冷却状态的记忆。]),
  (4, [#icon("nbt-long") *ttl*: 该记忆距离过期的游戏刻数。初始过期时间为80 gt。]),
  (4, [#icon("nbt-int") *value*: 该鹦鹉螺或僵尸鹦鹉螺是否处于冲刺攻击的冷却状态。]),
  (3, [#icon("nbt-compound") *minecraft:danger_detected_recently*: 适用于*犰狳*遇到危险蜷缩的记忆。]),
  (4, [#icon("nbt-long") *ttl*: 该记忆距离过期的游戏刻数。初始过期时间为60 gt。]),
  (4, [#icon("nbt-bool") *value*: 犰狳遇到危险时是否应该蜷缩。]),
  (3, [#icon("nbt-compound") *minecraft:dig_cooldown*: 适用于*监守者*钻入地下的倒计时的记忆。]),
  (4, [#icon("nbt-long") *ttl*: 该记忆距离过期的游戏刻数。初始过期时间为1200 gt。]),
  (4, [#icon("nbt-compound") *value*: 无数据，空白复合标签。]),
  (3, [#icon("nbt-compound") *minecraft:gaze_cooldown_ticks*: 适用于*骆驼*、*犰狳*、*铜傀儡*和*骆驼尸壳*凝视冷却时间的记忆。]),
  (4, [#icon("nbt-int") *value*: 此值介于 `150` 和 `250` 之间（含），该生物随机选择一个方向凝视后获得此记忆，每游戏刻减1，为 `0` 时抹去该记忆。]),
  (3, [#icon("nbt-compound") *minecraft:golem_detected_recently*: 适用于*村民*探测铁傀儡的记忆。]),
  (4, [#icon("nbt-long") *ttl*: 该记忆距离过期的游戏刻数。初始过期时间为599 gt。]),
  (4, [#icon("nbt-bool") *value*: 此村民是否在近期探测到铁傀儡，记忆存在时总是为 `true`。]),
  (3, [#icon("nbt-compound") *minecraft:has_hunting_cooldown*: 适用于*美西螈*、*青蛙*捕食冷却状态的记忆。]),
  (4, [#icon("nbt-long") *ttl*: 该记忆距离过期的游戏刻数。初始过期时间为2400 gt，为 `0l` 时生物才可以捕食。]),
  (4, [#icon("nbt-bool") *value*: 此美西螈或青蛙是否处于捕食冷却的状态，记忆存在时总是为 `true`。]),
  (3, [#icon("nbt-compound") *minecraft:home*: 适用于*村民*绑定床位置的记忆，也适用于*猪灵蛮兵*自身生成位置的记忆。]),
  (4, [#icon("nbt-long") *ttl*: 该记忆距离过期的游戏刻数。初始过期时间为2400 gt，为 `0l` 时生物才可以捕食。]),
  (4, [#icon("nbt-compound") *value*: 位置信息。]),
  (5, [#icon("nbt-string") *dimension*: 此位置所在的维度的命名空间ID。]),
  (5, [#icon("nbt-int_array") *pos*: 目标位置的方块坐标，列表内元素依次为$x$、$y$、$z$坐标。]),
  (3, [#icon("nbt-compound") *minecraft:hunted_recently*: 适用于*猪灵*猎捕疣猪兽的记忆。]),
  (4, [#icon("nbt-long") *ttl*: 该记忆距离过期的游戏刻数。初始过期时间不定，介于600 gt和2400 gt之间（含）。]),
  (4, [#icon("nbt-bool") *value*: 猪灵是否近期猎捕疣猪兽，记忆存在时总是为 `true`。]),
  (3, [#icon("nbt-compound") *minecraft:is_emerging*: 适用于*监守者*钻出地面的记忆。]),
  (4, [#icon("nbt-long") *ttl*: 该记忆距离过期的游戏刻数。初始过期时间为134 gt。]),
  (4, [#icon("nbt-compound") *value*: 无数据，空白复合标签。]),
  (3, [#icon("nbt-compound") *minecraft:is_in_water*: 适用于*青蛙*在水中的记忆。]),
  (4, [#icon("nbt-compound") *value*: 无数据，空白复合标签。]),
  (3, [#icon("nbt-compound") *minecraft:is_panicking*: 适用于*山羊*、*美西螈*、*悦灵*、*青蛙*、*蝌蚪*、*骆驼*、*嗅探兽*、*犰狳*、*小恶魂*、*铜傀儡*、*鹦鹉螺*、*僵尸鹦鹉螺*和*骆驼尸壳*慌乱状态的记忆。]),
  (4, [#icon("nbt-bool") *value*: 此生物是否处于慌乱状态，记忆存在时总是为 `true`。]),
  (3, [#icon("nbt-compound") *minecraft:is_pregnant*: 适用于*青蛙*怀孕的记忆。]),
  (4, [#icon("nbt-compound") *value*: 无数据，空白复合标签。]),
  (3, [#icon("nbt-compound") *minecraft:is_sniffing*: 适用于*监守者*嗅探行为的记忆。]),
  (4, [#icon("nbt-compound") *value*: 无数据，空白复合标签。]),
  (3, [#icon("nbt-compound") *minecraft:is_tempted*: 适用于*山羊*、*美西螈*、*青蛙*、*蝌蚪*、*骆驼*、*嗅探兽*、*犰狳*、*小恶魂*、*鹦鹉螺*、*僵尸鹦鹉螺*和*骆驼尸壳*被吸引的记忆。]),
  (4, [#icon("nbt-bool") *value*: 此生物是否被吸引。]),
  (3, [#icon("nbt-compound") *minecraft:item_pickup_cooldown_ticks*: 适用于*悦灵*捡起物品冷却时间的记忆。村民和猪灵也可以使用此记忆，但无法主动获取该记忆。]),
  (4, [#icon("nbt-int") *value*: 此生物捡起物品的冷却时间。捡起物品时此值被设为 `60`，此后该值每游戏刻减少 1，为 `0` 时去除此记忆。]),
  (3, [#icon("nbt-compound") *minecraft:job_site*: 适用于*村民*绑定工作站点的记忆。]),
  (4, [#icon("nbt-compound") *value*: 工作站点的位置信息。]),
  (5, [#icon("nbt-string") *dimension*: 工作站点所在的维度的命名空间ID。]),
  (5, [#icon("nbt-int_array") *pos*: 工作站点的方块坐标，列表内元素依次为$x$、$y$、$z$坐标。]),
  (3, [#icon("nbt-compound") *minecraft:last_slept*: 适用于*村民*上次睡觉时间的记忆。]),
  (4, [#icon("nbt-long") *value*: 该村民上次睡觉的游戏时间。]),
  (3, [#icon("nbt-compound") *minecraft:last_woken*: 适用于*村民*上次睡醒时间的记忆。]),
  (4, [#icon("nbt-long") *value*: 该村民上次睡醒的游戏时间。]),
  (3, [#icon("nbt-compound") *minecraft:last_worked_at_poi*: 适用于*村民*上次工作时间的记忆。]),
  (4, [#icon("nbt-long") *value*: 该村民上次睡醒的游戏时间。]),
  (3, [#icon("nbt-compound") *minecraft:liked_noteblock*: 适用于*悦灵*喜爱的音符盒的记忆。]),
  (4, [#icon("nbt-compound") *value*: 音符盒的位置信息。]),
  (5, [#icon("nbt-string") *dimension*: 音符盒所在的维度的命名空间ID。]),
  (5, [#icon("nbt-int_array") *pos*: 音符盒的方块坐标，列表内元素依次为$x$、$y$、$z$坐标。]),
  (3, [#icon("nbt-compound") *minecraft:liked_noteblock_cooldown_ticks*: 适用于*悦灵*听到音符盒声音后冷却时间的记忆。]),
  (4, [#icon("nbt-int") *value*: 悦灵捡起物品的冷却时间。悦灵捡起物品时此值被设为 `600`，此后该值每游戏刻减少1，为0时去除此记忆。]),
  (3, [#icon("nbt-compound") *minecraft:liked_player*: 适用于*悦灵*对给予其物品的玩家的记忆。]),
  (4, [#icon("nbt-int_array") *value*: 给予该悦灵物品的玩家的UUID。]),
  (3, [#icon("nbt-compound") *minecraft:long_jump_cooling_down*: 适用于*山羊*、*青蛙*长跳倒计时的记忆。]),
  (4, [#icon("nbt-int") *value*: 该生物的长跳倒计时。对于山羊，此项为介于600 gt和1200 gt之间（含）的值；对于青蛙，此项为介于100 gt和140 gt之间（含）的值。]),
  (3, [#icon("nbt-compound") *minecraft:meeting_point*: 适用于*村民*对于村庄会合点的记忆。]),
  (4, [#icon("nbt-compound") *value*: 村庄会合点的位置信息。]),
  (5, [#icon("nbt-string") *dimension*: 村庄会合点所在的维度的命名空间ID。]),
  (5, [#icon("nbt-int_array") *pos*: 村庄会合点的方块坐标，列表内元素依次为$x$、$y$、$z$坐标。]),
  (3, [#icon("nbt-compound") *minecraft:play_dead_ticks*: 适用于*美西螈*装死时间的记忆。]),
  (4, [#icon("nbt-int") *value*: 该美西螈装死的时间。美西螈准备装死时此值被设为 `200`，此后该值每游戏刻减少1，为 `0` 时去除此记忆。]),
  (3, [#icon("nbt-compound") *minecraft:potential_job_site*: 适用于*村民*将要绑定工作站点的记忆。]),
  (4, [#icon("nbt-compound") *value*: 该村民即将绑定的工作站点的位置信息。]),
  (5, [#icon("nbt-string") *dimension*: 工作站点所在的维度的命名空间ID。]),
  (5, [#icon("nbt-int_array") *pos*: 工作站点的方块坐标，列表内元素依次为$x$、$y$、$z$坐标。]),
  (3, [#icon("nbt-compound") *minecraft:ram_cooldown_ticks*: 适用于*山羊*冲撞冷却时间的记忆。]),
  (4, [#icon("nbt-int") *value*: 该山羊冲撞的冷却时间。当一次冲撞结束后，对于普通山羊该值介于600 gt和6000 gt之间（含），尖叫山羊介于100 gt与300 gt之间（含）。如果冲撞过程中目标消失，或者记忆值减为 `0` 时山羊未选择目标，对于普通山羊该值为600 gt，尖叫山羊为100 gt。该值每游戏刻减少1，为 `0` 时去除此记忆。]),
  (3, [#icon("nbt-compound") *minecraft:recent_projectile*: 适用于*监守者*觉察到异常弹射物的记忆。]),
  (4, [#icon("nbt-long") *ttl*: 该记忆距离过期的游戏刻数。初始过期时间为100 gt。]),
  (4, [#icon("nbt-compound") *value*: 无数据，空白复合标签。]),
  (3, [#icon("nbt-compound") *minecraft:roar_sound_cooldown*: 适用于*监守者*怒吼冷却时间的记忆。]),
  (4, [#icon("nbt-long") *ttl*: 该记忆距离过期的游戏刻数。初始过期时间为59 gt。]),
  (4, [#icon("nbt-compound") *value*: 无数据，空白复合标签。]),
  (3, [#icon("nbt-compound") *minecraft:roar_sound_delay*: 适用于*监守者*怒吼倒计时的记忆。]),
  (4, [#icon("nbt-long") *ttl*: 该记忆距离过期的游戏刻数。初始过期时间为25 gt。]),
  (4, [#icon("nbt-compound") *value*: 无数据，空白复合标签。]),
  (3, [#icon("nbt-compound") *minecraft:sniff_cooldown*: 适用于*监守者*、*嗅探兽*嗅探行为冷却时间的记忆。]),
  (4, [#icon("nbt-long") *ttl*: 该记忆距离过期的游戏刻数。对于监守者，初始过期时间为100 gt；对于监守者，初始过期时间为9600 gt。]),
  (4, [#icon("nbt-compound") *value*: 无数据，空白复合标签。]),
  (3, [#icon("nbt-compound") *minecraft:sniffer_explored_positions*: 适用于*嗅探兽*对以探索过的位置的记忆。]),
  (4, [#icon("nbt-list") *value*: 该嗅探兽所有以探索过的位置信息。]),
  (5, [#icon("nbt-compound") 一个位置。]),
  (6, [#icon("nbt-string") *dimension*: 该位置所在的维度的命名空间ID。]),
  (6, [#icon("nbt-int_array") *pos*: 该位置的方块坐标，列表内元素依次为$x$、$y$、$z$坐标。]),
  (3, [#icon("nbt-compound") *minecraft:sonic_boom_cooldown*: 适用于*监守者*远程攻击的冷却时间的记忆。]),
  (4, [#icon("nbt-long") *ttl*: 该记忆距离过期的游戏刻数。当监守者停止远程攻击或使用非远程攻击伤害生物时，初始过期时间为40 gt；当监守者察觉到目标时，初始过期时间为200 gt。]),
  (4, [#icon("nbt-compound") *value*: 无数据，空白复合标签。]),
  (3, [#icon("nbt-compound") *minecraft:sonic_boom_sound_cooldown*: 适用于*监守者*远程攻击充能前的冷却时间的记忆。]),
  (4, [#icon("nbt-long") *ttl*: 该记忆距离过期的游戏刻数。初始过期时间为26 gt。]),
  (4, [#icon("nbt-compound") *value*: 无数据，空白复合标签。]),
  (3, [#icon("nbt-compound") *minecraft:sonic_boom_sound_delay*: 适用于*监守者*远程攻击倒计时的记忆。]),
  (4, [#icon("nbt-long") *ttl*: 该记忆距离过期的游戏刻数。初始过期时间为34 gt。]),
  (4, [#icon("nbt-compound") *value*: 无数据，空白复合标签。]),
  (3, [#icon("nbt-compound") *minecraft:temptation_cooldown_ticks*: 适用于*山羊*、*美西螈*、*青蛙*、*蝌蚪*、*骆驼*、*犰狳*、*小恶魂*、*鹦鹉螺*、*僵尸鹦鹉螺*和*骆驼尸壳*被玩家吸引的冷却时间的记忆。]),
  (4, [#icon("nbt-int") *value*: 该生物被玩家两次吸引的时间间隔，此值为 `100`，每游戏刻减少1，为 `0` 时去除此记忆。]),
  (3, [#icon("nbt-compound") *minecraft:touch_cooldown*: 适用于*监守者*对推动感受的记忆。]),
  (4, [#icon("nbt-long") *ttl*: 该记忆距离过期的游戏刻数。初始过期时间为20 gt。]),
  (4, [#icon("nbt-compound") *value*: 无数据，空白复合标签。]),
  (3, [#icon("nbt-compound") *minecraft:universal_anger*: 适用于*猪灵*对玩家全局愤怒的记忆，游戏规则 `universal_anger` 为 `true` 时获得此记忆。]),
  (4, [#icon("nbt-long") *ttl*: 该记忆距离过期的游戏刻数。初始过期时间为600 gt。]),
  (4, [#icon("nbt-bool") *value*: 猪灵是否对玩家有着全局的愤怒，记忆存在时总是为 `true`。]),
  (3, [#icon("nbt-compound") *minecraft:vibration_cooldown*: 适用于*监守者*监听振动冷却时间的记忆。]),
  (4, [#icon("nbt-long") *ttl*: 该记忆距离过期的游戏刻数。初始过期时间为40 gt。]),
  (4, [#icon("nbt-compound") *value*: 无数据，空白复合标签。]),
  (3, [#icon("nbt-compound") *minecraft:visited_block_positions*: 适用于*铜傀儡*对箱子的记忆。]),
  (4, [#icon("nbt-long") *ttl*: 该记忆距离过期的游戏刻数。初始过期时间为6000 gt。]),
  (4, [#icon("nbt-list") *value*: 该铜傀儡记忆的箱子位置信息。]),
  (5, [#icon("nbt-compound") 一个箱子。]),
  (6, [#icon("nbt-string") *dimension*: 该箱子所在的维度的命名空间ID。]),
  (6, [#icon("nbt-int_array") *pos*: 该箱子的方块坐标，列表内元素依次为$x$、$y$、$z$坐标。]),
  (1, [#icon("nbt-list") *current_explosion_impact_pos*: 此生物被所有形式的爆炸击退时的坐标，列表内元素顺序不可改变。#icon("nbt-int") `current_impulse_context_reset_grace_time` 为 `0` 时此字段被删除。]),
  (2, [#icon("nbt-double") $x$坐标。]),
  (2, [#icon("nbt-double") $y$坐标。]),
  (2, [#icon("nbt-double") $z$坐标。]),
  (1, [#icon("nbt-int") *#underline[current_impulse_context_reset_grace_time]*: 爆炸击退减少摔落伤害的最长时间，单位为游戏刻。]),
  (1, [#icon("nbt-short") *#underline[DeathTime]*: 距离生物死亡而被删除的时间。生物存活时该值为 `0s`，死亡后每游戏刻增加 `1s`，直到该值达到 `20s` 时生物被删除。]),
  (1, [#icon("nbt-compound") *equipment*: 生物的装备。]),
  (2, [#icon("nbt-compound") *\<槽位>*: 在此槽位上装备的物品。有效的槽位有 `mainhand`、`offhand`、`feet`、`legs`、`chest`、​`head`、`body` 和 `saddle`。]),
  (3, link(<data:item_data>)[无槽位物品格式]),
  (1, [#icon("nbt-bool") *FallFlying*: 该生物是否处于滑翔状态。]),
  (1, [#icon("nbt-float") *Health*: 该生物的生命值。]),
  (1, [#icon("nbt-short") *#underline[HurtTime]*: 该生物受伤后伤害免疫阶段（变红）的剩余时间，初始为10 gt，每游戏刻减1。]),
  (1, [#icon("nbt-int_array") *last_hurt_by_mob*: 当前最后一次攻击该生物的生物的UUID。]),
  (1, [#icon("nbt-int_array") *last_hurt_by_player*: 当前最后一次攻击该生物的玩家的UUID。]),
  (1, [#icon("nbt-int") *last_hurt_by_player_memory_time*: 生物被玩家攻击后该值为 `100`（单位为游戏刻），每游戏刻减少1，此值降到 `0` 以下后清除 #icon("nbt-int_array") `last_hurt_by_player` 的数据，并删除此字段。]),
  (1, [#icon("nbt-compound") *locator_bar_icon*: 生物的路径点图标。]),
  (2, [#icon("nbt-int")#icon("nbt-list") *color*: 此生物路径点的图标颜色，可以用 #icon("nbt-int") 整型指定RGB颜色，对二进制而言，每八位表示一个通道，从高到低依次为R、G、B通道。也可以用 #icon("nbt-list") 列表分别指定每个通道。游戏在存储时一律存储为 #icon("nbt-int") 整型。]),
  (3, [*若使用 #icon("nbt-list") 列表形式，则包含以下字段：*], false),
  (3, [#icon("nbt-float") R通道分量，表示红色值。]),
  (3, [#icon("nbt-float") G通道分量，表示绿色值。]),
  (3, [#icon("nbt-float") B通道分量，表示蓝色值。]),
  (2, [#icon("nbt-string") *style*: 路径点样式的命名空间ID。]),
  (1, [#icon("nbt-int_array") *sleeping_pos*: 该生物所睡床的坐标，依次为$x$、$y$、$z$坐标。此标签仅在该生物睡觉时存在。]),
  (1, [#icon("nbt-string") *Team*: 可选，该生物所在的队伍。]),
  (1, [#icon("nbt-int") *ticks_since_last_hurt_by_mob*: 生物最近一次被生物攻击后距离上次攻击的游戏刻数。])
)
#heading(level: 4, numbering: none, [AI生物共通标签（Java类名 `Mob`）])
所有拥有AI的生物都拥有以下字段：
#tree(
  (0, [#icon("nbt-compound") 根标签]),
  (1, [#icon("nbt-bool") *#underline[CanPickUpLoot]*: 此生物是否可以捡起并使用战利品。]),
  (1, [#icon("nbt-string") *DeathLootTable*: 此生物死亡时掉落物使用的战利品表。]),
  (1, [#icon("nbt-long") *DeathLootTableSeed*: 生成战利品使用的种子，如果不存在该标签或值为 `0l` 则使用随机序列，仅当 #icon("nbt-string") `DeathLootTable` 存在时有效。]),
  (1, [#icon("nbt-compound") *drop_chances*: 此生物死亡时各槽位的物品掉落的概率。]),
  (2, [#icon("nbt-float") *\<装备槽位>*: 该槽位的物品掉落的概率，默认为 `0.85f`。]),
  (1, [#icon("nbt-int_array") *home_pos*: 此生物活动范围的中心。]),
  (1, [#icon("nbt-int") *home_radius*: 此生物活动范围的半径。]),
  (1, [#icon("nbt-int_array")#icon("nbt-compound") *leash*: 当此生物被栓绳拴住时，存在该标签。]),
  (2, [*若使用 #icon("nbt-int_array") 整型数组形式，则表示此生物被栓在栅栏上，数组内有3个元素，依次为栅栏的3个方块坐标值。*], false),
  (2, [*若使用 #icon("nbt-compound") 复合标签形式，则表示此生物被栓在另一个实体上，且有以下字段：*], false),
  (2, [#icon("nbt-int_array") *#underline[UUID]*: 拴住此生物的实体的UUID。]),
  (1, [#icon("nbt-bool") *#underline[LeftHanded]*: 此生物的主手是否为左手。]),
  (1, [#icon("nbt-bool") *NoAI*: 此生物的AI是否被禁用，注意禁用AI不会使此生物静音。]),
  (1, [#icon("nbt-bool") *#underline[PersistenceRequired]*: 此生物是否会被自然删除。])
)
#heading(level: 4, numbering: none, [可成长生物共通标签（Java类名 `AgeableMob`）])
所有可以由幼体成长为成体的生物都拥有以下字段：
#tree(
  (0, [#icon("nbt-compound") 根标签]),
  (1, [#icon("nbt-int") *#underline[Age]*: 此生物的年龄。若生物为幼体，该值为负数；若生物为成体，该值为非负数。正数表示此生物能再次繁衍的冷却时间。]),
  (1, [#icon("nbt-bool") *#underline[AgeLocked]*: 此生物的年龄是否被冻结。]),
  (1, [#icon("nbt-int") *#underline[ForcedAge]*: 此生物成年后被赋予的年龄值。])
)
#heading(level: 4, numbering: none, [动物共通标签（Java类名 `Animal`）])
所有可以繁殖的生物都拥有以下字段：
#tree(
  (0, [#icon("nbt-compound") 根标签]),
  (1, [#icon("nbt-int") *#underline[InLove]*: 此生物距离求爱模式结束的剩余时间，单位为游戏刻。当生物进入求爱模式时，此值会被设为 `600`，每游戏刻减1，减为 `0` 时，终止求爱模式。只有当 #icon("nbt-int") `Age` 的值为 `0` 时，该字段才能设为正值。]),
  (1, [#icon("nbt-int_array") *LoveCause*: 使此生物进入求爱模式的实体的UUID。])
)
#heading(level: 4, numbering: none, [中立型生物共通标签（Java类名 `NeutralMob`）])
所有中立型生物都拥有以下字段：
#tree(
  (0, [#icon("nbt-compound") 根标签]),
  (1, [#icon("nbt-long") *#underline[anger_end_time]*: 此生物保持敌对状态的剩余时间。]),
  (1, [#icon("nbt-int_array") *LoveCause*: 使此生物进入求爱模式的实体的UUID。])
)
#heading(level: 4, numbering: none, [袭击者共通标签（Java类名 `Raider`）])
所有能够参与袭击的生物都拥有以下字段：
#tree(
  (0, [#icon("nbt-compound") 根标签]),
  (1, [#icon("nbt-bool") *#underline[CanJoinRaid]*: 此生物能否参与袭击。]),
  (1, [#icon("nbt-int_array") *patrol_target*: 灾厄巡逻队正在前往的位置，含有三个元素，依次为$x$、$y$、$z$坐标。]),
  (1, [#icon("nbt-bool") *#underline[PatrolLeader]*: 此生物是否为灾厄巡逻队的袭击队长。]),
  (1, [#icon("nbt-bool") *#underline[Patrolling]*: 此生物是否正在巡逻。]),
  (1, [#icon("nbt-bool") *RaidId*: 此生物所属的袭击的ID。]),
  (1, [#icon("nbt-bool") *#underline[Wave]*: 此生物所属的袭击波数。])
)
#heading(level: 4, numbering: none, [弹射物共通标签（Java类名 `Projectile`）])
#tree(
  (0, [#icon("nbt-compound") 根标签]),
  (1, [#icon("nbt-bool") *#underline[HasBeenShot]*: 此弹射物存在时间是否超过1 gt。]),
  (1, [#icon("nbt-bool") *LeftOwner*: 此弹射物是否已离开发射者的碰撞箱。]),
  (1, [#icon("nbt-int_array") *Owner*: 此弹射物发射者的UUID。])
)