name: Continuous Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk fonts-noto-cjk-extra

      - name: List files for debugging
        run: |
          ls -R

      - name: Setup Typst
        uses: typst-community/setup-typst@v3

      - name: Compile
        run: typst compile "命令与原版开发基础.typ" "命令与原版开发基础.pdf"

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: 命令与原版开发基础.pdf